/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bankmanagementsystem;

import java.util.Random;
import javax.swing.*;

/**
 *
 * @author Fatima Butt
 */
public class CustomerPortalForm extends javax.swing.JFrame {
       ConnectionToDB CTD = new ConnectionToDB();
       CustomerPortal CP = new CustomerPortal();
       Accounts acc = new Accounts();
    /** Creates new form CustomerPortalForm */
    public CustomerPortalForm() {
        initComponents();
    }
    int random;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        CusIDTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AccNumTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddAcc = new javax.swing.JButton();
        AccType = new javax.swing.JComboBox<>();
        Random = new javax.swing.JButton();
        AddBal = new javax.swing.JButton();
        BalanceTxt = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CusIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusIDTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel3.setText("Account Number");

        AccNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNumTxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel10.setText("Account Type");

        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel4.setText("Balance");

        AddAcc.setText("Add Account");
        AddAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccActionPerformed(evt);
            }
        });

        AccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current", "Saving"}));
        AccType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AccTypeItemStateChanged(evt);
            }
        });
        AccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccTypeActionPerformed(evt);
            }
        });

        Random.setText("Random");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        AddBal.setText("Add Balance");
        AddBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBalActionPerformed(evt);
            }
        });

        BalanceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceTxtActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel5.setText("CUSTOMER PORTAL");

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddAcc)
                                .addGap(18, 18, 18)
                                .addComponent(AddBal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(166, 166, 166)
                                .addComponent(CusIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AccNumTxt)
                                            .addComponent(AccType, 0, 159, Short.MAX_VALUE)
                                            .addComponent(BalanceTxt))))
                                .addGap(18, 18, 18)
                                .addComponent(Random))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel5)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addComponent(CusIDTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AccNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Random))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAcc)
                    .addComponent(AddBal))
                .addGap(65, 65, 65)
                .addComponent(back)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CusIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusIDTxtActionPerformed

    private void AccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccTypeActionPerformed
        
    }//GEN-LAST:event_AccTypeActionPerformed

    private void AccTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AccTypeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_AccTypeItemStateChanged

    private void AccNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNumTxtActionPerformed
        
    }//GEN-LAST:event_AccNumTxtActionPerformed

    private void AddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccActionPerformed
         
    
        int ID = Integer.parseInt(CusIDTxt.getText());
        int AN = Integer.parseInt(AccNumTxt.getText());
        String AT = (String) AccType.getSelectedItem();
        boolean b =CP.AddAccount(ID,AN, AT);
        if(b)
        {
            JOptionPane.showMessageDialog(null,"Inserted");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Error");
        }
        
    }//GEN-LAST:event_AddAccActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        Random rand = new Random();
        int ran=999999;
        random = rand.nextInt(ran);
        AccNumTxt.setText(String.valueOf(random));
    }//GEN-LAST:event_RandomActionPerformed

    private void AddBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBalActionPerformed
        
        int ID = Integer.parseInt(CusIDTxt.getText());
        
        float BAL = Float.parseFloat(BalanceTxt.getText());
        boolean b =acc.AddBalance(ID, (int) BAL);
        if(b)
        {
            JOptionPane.showMessageDialog(null, "Success");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
        
        
        
        
    }//GEN-LAST:event_AddBalActionPerformed

    private void BalanceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceTxtActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        Bank_Portal_Form BPF = new Bank_Portal_Form();
        BPF.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        CusIDTxt.setText("");
        AccNumTxt.setText("");
        BalanceTxt.setText("");
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPortalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPortalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPortalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPortalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPortalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNumTxt;
    private javax.swing.JComboBox<String> AccType;
    private javax.swing.JButton AddAcc;
    private javax.swing.JButton AddBal;
    private javax.swing.JTextField BalanceTxt;
    private javax.swing.JTextField CusIDTxt;
    private javax.swing.JButton Random;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
